package scrreplayparser.commands;

import java.util.HashMap;
import java.util.Map;

public enum Order {
  DIE(0, "Die"),
  STOP(1, "Stop"),
  GUARD(2, "Guard"),
  PLAYER_GUARD(3, "PlayerGuard"),
  TURRET_GUARD(4, "TurretGuard"),
  BUNKER_GUARD(5, "BunkerGuard"),
  MOVE(6, "Move"),
  REAVER_STOP(7, "ReaverStop"),
  ATTACK_1(8, "Attack1"),
  ATTACK_2(9, "Attack2"),
  ATTACK_UNIT(10, "AttackUnit"),
  ATTACK_FIXED_RANGE(11, "AttackFixedRange"),
  ATTACK_TILE(12, "AttackTile"),
  HOVER(13, "Hover"),
  ATTACK_MOVE(14, "AttackMove"),
  INFESTED_COMMAND_CENTER(15, "InfestedCommandCenter"),
  UNUSED_NOTHING(16, "UnusedNothing"),
  UNUSED_POWERUP(17, "UnusedPowerup"),
  TOWER_GUARD(18, "TowerGuard"),
  TOWER_ATTACK(19, "TowerAttack"),
  VULTURE_MINE(20, "VultureMine"),
  STAY_IN_RANGE(21, "StayInRange"),
  TURRET_ATTACK(22, "TurretAttack"),
  NOTHING(23, "Nothing"),
  UNUSED__24(24, "Unused_24"),
  DRONE_START_BUILD(25, "DroneStartBuild"),
  DRONE_BUILD(26, "DroneBuild"),
  CAST_INFESTATION(27, "CastInfestation"),
  MOVE_TO_INFEST(28, "MoveToInfest"),
  INFESTING_COMMAND_CENTER(29, "InfestingCommandCenter"),
  PLACE_BUILDING(30, "PlaceBuilding"),
  PLACE_PROTOSS_BUILDING(31, "PlaceProtossBuilding"),
  CREATE_PROTOSS_BUILDING(32, "CreateProtossBuilding"),
  CONSTRUCTING_BUILDING(33, "ConstructingBuilding"),
  REPAIR(34, "Repair"),
  MOVE_TO_REPAIR(35, "MoveToRepair"),
  PLACE_ADDON(36, "PlaceAddon"),
  BUILD_ADDON(37, "BuildAddon"),
  TRAIN(38, "Train"),
  RALLY_POINT_UNIT(39, "RallyPointUnit"),
  RALLY_POINT_TILE(40, "RallyPointTile"),
  ZERG_BIRTH(41, "ZergBirth"),
  ZERG_UNIT_MORPH(42, "ZergUnitMorph"),
  ZERG_BUILDING_MORPH(43, "ZergBuildingMorph"),
  INCOMPLETE_BUILDING(44, "IncompleteBuilding"),
  INCOMPLETE_MORPHING(45, "IncompleteMorphing"),
  BUILD_NYDUS_EXIT(46, "BuildNydusExit"),
  ENTER_NYDUS_CANAL(47, "EnterNydusCanal"),
  INCOMPLETE_WARPING(48, "IncompleteWarping"),
  FOLLOW(49, "Follow"),
  CARRIER(50, "Carrier"),
  REAVER_CARRIER_MOVE(51, "ReaverCarrierMove"),
  CARRIER_STOP(52, "CarrierStop"),
  CARRIER_ATTACK(53, "CarrierAttack"),
  CARRIER_MOVE_TO_ATTACK(54, "CarrierMoveToAttack"),
  CARRIER_IGNORE_2(55, "CarrierIgnore2"),
  CARRIER_FIGHT(56, "CarrierFight"),
  CARRIER_HOLD_POSITION(57, "CarrierHoldPosition"),
  REAVER(58, "Reaver"),
  REAVER_ATTACK(59, "ReaverAttack"),
  REAVER_MOVE_TO_ATTACK(60, "ReaverMoveToAttack"),
  REAVER_FIGHT(61, "ReaverFight"),
  REAVER_HOLD_POSITION(62, "ReaverHoldPosition"),
  TRAIN_FIGHTER(63, "TrainFighter"),
  INTERCEPTOR_ATTACK(64, "InterceptorAttack"),
  SCARAB_ATTACK(65, "ScarabAttack"),
  RECHARGE_SHIELDS_UNIT(66, "RechargeShieldsUnit"),
  RECHARGE_SHIELDS_BATTERY(67, "RechargeShieldsBattery"),
  SHIELD_BATTERY(68, "ShieldBattery"),
  INTERCEPTOR_RETURN(69, "InterceptorReturn"),
  DRONE_LAND(70, "DroneLand"),
  BUILDING_LAND(71, "BuildingLand"),
  BUILDING_LIFT_OFF(72, "BuildingLiftOff"),
  DRONE_LIFT_OFF(73, "DroneLiftOff"),
  LIFTING_OFF(74, "LiftingOff"),
  RESEARCH_TECH(75, "ResearchTech"),
  UPGRADE(76, "Upgrade"),
  LARVA(77, "Larva"),
  SPAWNING_LARVA(78, "SpawningLarva"),
  HARVEST_1(79, "Harvest1"),
  HARVEST_2(80, "Harvest2"),
  MOVE_TO_GAS(81, "MoveToGas"),
  WAIT_FOR_GAS(82, "WaitForGas"),
  HARVEST_GAS(83, "HarvestGas"),
  RETURN_GAS(84, "ReturnGas"),
  MOVE_TO_MINERALS(85, "MoveToMinerals"),
  WAIT_FOR_MINERALS(86, "WaitForMinerals"),
  MINING_MINERALS(87, "MiningMinerals"),
  HARVEST_3(88, "Harvest3"),
  HARVEST_4(89, "Harvest4"),
  RETURN_MINERALS(90, "ReturnMinerals"),
  INTERRUPTED(91, "Interrupted"),
  ENTER_TRANSPORT(92, "EnterTransport"),
  PICKUP_IDLE(93, "PickupIdle"),
  PICKUP_TRANSPORT(94, "PickupTransport"),
  PICKUP_BUNKER(95, "PickupBunker"),
  PICKUP_4(96, "Pickup4"),
  POWERUP_IDLE(97, "PowerupIdle"),
  SIEGING(98, "Sieging"),
  UNSIEGING(99, "Unsieging"),
  WATCH_TARGET(100, "WatchTarget"),
  INIT_CREEP_GROWTH(101, "InitCreepGrowth"),
  SPREAD_CREEP(102, "SpreadCreep"),
  STOPPING_CREEP_GROWTH(103, "StoppingCreepGrowth"),
  GUARDIAN_ASPECT(104, "GuardianAspect"),
  ARCHON_WARP(105, "ArchonWarp"),
  COMPLETING_ARCHON_SUMMON(106, "CompletingArchonSummon"),
  HOLD_POSITION(107, "HoldPosition"),
  QUEEN_HOLD_POSITION(108, "QueenHoldPosition"),
  CLOAK(109, "Cloak"),
  DECLOAK(110, "Decloak"),
  UNLOAD(111, "Unload"),
  MOVE_UNLOAD(112, "MoveUnload"),
  FIRE_YAMATO_GUN(113, "FireYamatoGun"),
  MOVE_TO_FIRE_YAMATO_GUN(114, "MoveToFireYamatoGun"),
  CAST_LOCKDOWN(115, "CastLockdown"),
  BURROWING(116, "Burrowing"),
  BURROWED(117, "Burrowed"),
  UNBURROWING(118, "Unburrowing"),
  CAST_DARK_SWARM(119, "CastDarkSwarm"),
  CAST_PARASITE(120, "CastParasite"),
  CAST_SPAWN_BROODLINGS(121, "CastSpawnBroodlings"),
  CAST_EMP_SHOCKWAVE(122, "CastEMPShockwave"),
  NUKE_WAIT(123, "NukeWait"),
  NUKE_TRAIN(124, "NukeTrain"),
  NUKE_LAUNCH(125, "NukeLaunch"),
  NUKE_PAINT(126, "NukePaint"),
  NUKE_UNIT(127, "NukeUnit"),
  CAST_NUCLEAR_STRIKE(-128, "CastNuclearStrike"),
  NUKE_TRACK(-127, "NukeTrack"),
  INITIALIZE_ARBITER(-126, "InitializeArbiter"),
  CLOAK_NEARBY_UNITS(-125, "CloakNearbyUnits"),
  PLACE_MINE(-124, "PlaceMine"),
  RIGHT_CLICK_ACTION(-123, "RightClickAction"),
  SUICIDE_UNIT(-122, "SuicideUnit"),
  SUICIDE_LOCATION(-121, "SuicideLocation"),
  SUICIDE_HOLD_POSITION(-120, "SuicideHoldPosition"),
  CAST_RECALL(-119, "CastRecall"),
  TELEPORT(-118, "Teleport"),
  CAST_SCANNER_SWEEP(-117, "CastScannerSweep"),
  SCANNER(-116, "Scanner"),
  CAST_DEFENSIVE_MATRIX(-115, "CastDefensiveMatrix"),
  CAST_PSIONIC_STORM(-114, "CastPsionicStorm"),
  CAST_IRRADIATE(-113, "CastIrradiate"),
  CAST_PLAGUE(-112, "CastPlague"),
  CAST_CONSUME(-111, "CastConsume"),
  CAST_ENSNARE(-110, "CastEnsnare"),
  CAST_STASIS_FIELD(-109, "CastStasisField"),
  CAST_HALLUCINATION(-108, "CastHallucination"),
  HALLUCINATION_2(-107, "Hallucination2"),
  RESET_COLLISION(-106, "ResetCollision"),
  RESET_HARVEST_COLLISION(-105, "ResetHarvestCollision"),
  PATROL(-104, "Patrol"),
  CTFCOP_INIT(-103, "CTFCOPInit"),
  CTFCOP_STARTED(-102, "CTFCOPStarted"),
  CTFCOP_2(-101, "CTFCOP2"),
  COMPUTER_AI(-100, "ComputerAI"),
  ATK_MOVE_EP(-99, "AtkMoveEP"),
  HARASS_MOVE(-98, "HarassMove"),
  AI_PATROL(-97, "AIPatrol"),
  GUARD_POST(-96, "GuardPost"),
  RESCUE_PASSIVE(-95, "RescuePassive"),
  NEUTRAL(-94, "Neutral"),
  COMPUTER_RETURN(-93, "ComputerReturn"),
  INITIALIZE_PSI_PROVIDER(-92, "InitializePsiProvider"),
  SELF_DESTRUCTING(-91, "SelfDestructing"),
  CRITTER(-90, "Critter"),
  HIDDEN_GUN(-89, "HiddenGun"),
  OPEN_DOOR(-88, "OpenDoor"),
  CLOSE_DOOR(-87, "CloseDoor"),
  HIDE_TRAP(-86, "HideTrap"),
  REVEAL_TRAP(-85, "RevealTrap"),
  ENABLE_DOODAD(-84, "EnableDoodad"),
  DISABLE_DOODAD(-83, "DisableDoodad"),
  WARP_IN(-82, "WarpIn"),
  MEDIC(-81, "Medic"),
  MEDIC_HEAL(-80, "MedicHeal"),
  HEAL_MOVE(-79, "HealMove"),
  MEDIC_HOLD_POSITION(-78, "MedicHoldPosition"),
  MEDIC_HEAL_TO_IDLE(-77, "MedicHealToIdle"),
  CAST_RESTORATION(-76, "CastRestoration"),
  CAST_DISRUPTION_WEB(-75, "CastDisruptionWeb"),
  CAST_MIND_CONTROL(-74, "CastMindControl"),
  DARK_ARCHON_MELD(-73, "DarkArchonMeld"),
  CAST_FEEDBACK(-72, "CastFeedback"),
  CAST_OPTICAL_FLARE(-71, "CastOpticalFlare"),
  CAST_MAELSTROM(-70, "CastMaelstrom"),
  JUNK_YARD_DOG(-69, "JunkYardDog"),
  FATAL(-68, "Fatal"),
  NONE(-67, "None"),
  UNKNOWN(-103, "Unknown");
  
  int id;
  
  String name;
  
  private static final Map<Integer, Order> lookupByByte;
  
  Order(int paramInt1, String paramString1) {
    this.id = paramInt1;
    this.name = paramString1;
  }
  
  public String getName() {
    return this.name;
  }
  
  public static Order getByID(int paramInt) {
    Order order1 = lookupByByte.get(Integer.valueOf(paramInt));
    if (order1 != null)
      return order1; 
    Order order2 = UNKNOWN;
    order2.id = paramInt;
    return order2;
  }
  
  static {
    lookupByByte = new HashMap<>();
    for (Order order : values())
      lookupByByte.put(Integer.valueOf(order.id), order); 
    lookupByByte.remove(Integer.valueOf(153));
  }
}
